import turtle
turtle.speed(10)
for i in range (4):
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.rt(90)
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.rt(90)
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.rt(90)
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.lt(90)
    turtle.fd(50)
    turtle.rt(90)
    turtle.fd(50)   

turtle.penup()
turtle.lt(90)
turtle.forward(400)
turtle.pendown()
turtle.rt(10)
turtle.fd(100)

turtle.done